name: Test Build PR Code

concurrency: Test-${{ github.ref }}
on:
  pull_request:
    branches:
      - '**'
    paths: 
      - "**.ts"
      # Ignore website directory changes as test deploy workflow will handle them.
      - "!website/**"
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Test build PR Code
        run: npx tsc --noEmit
